services:
  - type: web
    plan: free
    name: docuseal
    env: docker
    autoDeploy: false
    repo: https://github.com/PoomGamerE/docuseal-render-extdb.git
    envVars:
      - key: DATABASE_URL
        value: postgres://<username>:<password>@<host>:<port>/<dbname>?sslmode=require
      - key: SECRET_KEY_BASE
        generateValue: true
